SELECT *
FROM STUDENT
WHERE STU_GENDER = 'F';

SELECT * FROM professor;

SELECT *
FROM PROFESSOR
WHERE LENGTH(ID)>=6;

UPDATE PROFESSOR
SET
    PAY = PAY + 50
    WHERE LENGTH(ID)>=6;
    
ROLLBACK;  
    
DELETE FROM PROFESSOR WHERE ID < 6;

SELECT * FROM STUDENT;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES ('12345678', '김예슬', '기계');

INSERT INTO STUDENT
VALUES ('12341234', '김철수', '전기전자', 1, 'A', 'M', 175, NULL);