--1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오
--(STUDENT, ENROL)

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) 평균
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;


--2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.
--(STUDENT, ENROL, SUBJECT)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO, STU_NAME, STU_GRADE, E.ENR_GRADE, SUB_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_PROF = '강종영';


--3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
--- 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT 

--4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE AVG(ENR_GRADE) < ENR_GRADE
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;


--5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.
--(EMP, SALGRADE)
SELECT * FROM EMP;
SELECT * FROM salgrade;

SELECT EMPNO, ENAME, GRADE, DECODE(ENAME, MGR, ENAME)
FROM EMP E
INNER JOIN salgrade S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
--6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력
--(EMP, SALGRADE, DEPT)
SELECT * FROM EMP;
SELECT * FROM salgrade;
SELECT * FROM DEPT;

SELECT DNAME, AVG(GRADE)
FROM DEPT D
INNER JOIN EMP E ON D.DEPTNO = e.deptno
INNER JOIN salgrade S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DNAME, LOC;

--7. 인문대학에 속한 교수의 이름을 모두 출력하시오.
--(PROFESSOR, DEPARTMENT)
SELECT * FROM professor;
SELECT * FROM department;

SELECT *
FROM 



​